### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3

### ISSUE THREAD

**Issue by arielivandiaz** [elbayadm/attn2d#11]
I have this error, some solution please?

```
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    train(params)
  File "train.py", line 24, in train
    src_loader, trg_loader = ReadData(params['data'], params['modelname'])
  File "/home/ariel/CODE/attn2d/nmt/loader/__init__.py", line 14, in ReadData
    src_loader = textDataLoader(dataparams, job_name=job_name)
  File "/home/ariel/CODE/attn2d/nmt/loader/dataloader.py", line 16, in __init__
    infos = pickle.load(open(params['infos'], 'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

thanks!

**Comment by elbayadm** [comment]
Hi @arielivandiaz , 
I've never faced this issue but I think that either the data saved after running preprocess.py is corrupted or that it was pickled with python2.
You can re-preprocess your data or  specify the encoding when loading the pickle files:
` pickle.load(file, encoding='iso-8859-1') `

**Comment by arielivandiaz** [comment]
Thanks very much!
