### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by sancolo** [elbayadm/attn2d#12]
Hi, 
This error ocurs when i run:
$ python3 train.py -c config/l24.yaml
. . . . 
Layer 21: in_channels = 800
Layer 22: in_channels = 832
Layer 23: in_channels = 864
Adding the usual trans
Tying the decoder weights
09/04 17:28:16 Output channels: 128
09/04 17:28:16 num. model params: 7185836
09/04 17:28:16 Default ML loss
base lr: 0.0005
09/04 17:28:20 updating the lr wrt loss
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    train(params)
  File "train.py", line 61, in train
    losses, batch_size, ntokens = trainer.step(data_src, data_trg)
  File "/home/santiago/attn2d/nmt/trainer.py", line 215, in step
    decoder_logit = self.model(data_src, data_trg)
  File "/home/santiago/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/santiago/attn2d/nmt/models/convs2s2D.py", line 207, in forward
    X = self._forward(X, data_src['lengths'])  #, mask)
  File "/home/santiago/attn2d/nmt/models/convs2s2D.py", line 225, in _forward
    X = self.net(X)
  File "/home/santiago/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/santiago/attn2d/nmt/models/densenet.py", line 349, in forward
    return self.features(x.contiguous())
  File "/home/santiago/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/santiago/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/santiago/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/santiago/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/santiago/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/santiago/attn2d/nmt/models/densenet.py", line 66, in forward
    new_features = super(_DenseLayer, self).forward(x)
  File "/home/santiago/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/santiago/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/santiago/attn2d/nmt/models/conv2d.py", line 88, in forward
    return super(MaskedConv2d, self).forward(x)
  File "/home/santiago/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

I run it on a nvidia card with 6G of RAM
Can you help me?
Thank you in advanced

**Comment by elbayadm** [comment]
Hi @sancolo,
You would need at least 8G of RAM to train small models (12 dense layers) with the default batch size of 16. Otherwise, you can try reducing the number of layers, the network's growth or the batch size in the config file.

> network :
  num_layers : 12
  growth_rate : 16

> data:
  batch_size: 16

 I hope this helps.
