### ISSUE TITLE
ModuleNotFoundError: No module named 'nmt.loader.pair_loader'

### ISSUE THREAD

**Issue by koszilard** [elbayadm/attn2d#7]
Hi, as title says, I got this error:

Traceback (most recent call last):
  File "/home//repos/attn2d/train.py", line 84, in <module>
    train(params)
  File "/home//repos/attn2d/train.py", line 20, in train
    from nmt.trainer import Trainer
  File "/home//repos/attn2d/nmt/trainer.py", line 17, in <module>
    from nmt.loader.pair_loader import DataPair
ModuleNotFoundError: No module named 'nmt.loader.pair_loader'

**Comment by elbayadm** [comment]
Hi,
You should update to the latest commit which included nmt/loader/pair_loader.py
